# ' @title: HateSpeechAPI Function classifying all the texts in a data frame.

#' This function allows you to build the needed list for the API to classify the text.
#' @param api_token string of the  token from your personal API access
#' @param endpoint character string with the name of the endpoint
#' @param data data frame with the text variable to classify
#' @param query query of texts to classify in form of a list generated by query_maker().
#' @param text_name character string with the name of the text variable to classify.

#' @return a vector with predictions
#' @export
#'
#' @examples
#' \dontrun{
#' predictions <- classify_data(api_token = "", endpoint = "classify", data = df)
#' }

#' @importFrom dplyr select
#' @importFrom httr POST
#' @importFrom httr content_type_json
#' @importFrom httr content
#' @importFrom httr config
#' @importFrom jsonlite fromJSON
#' @importFrom stringr str_trunc

##################################################################################################
# Classify Data Frame Function
##################################################################################################
classify_data <- function(api_token = NULL, endpoint = "classify",  query = NULL, data = NULL, text_name = NULL){
  if(is.null(api_token) & is.null(endpoint) & (is.null(data) | is.null(query))){
    stop("Please add all necessary agruments to the classify function!\n")
  }

  if(is.null(query)){
    if(is.null(data)){
      stop("Please add either a query for the API or a Data Frame to classify texts with one of the API endpoints.\n")
    }
  }

  if(is.null(api_token)){
    stop("Please add the API token to the function!\n")
  }

  if(is.null(data)){
    if(is.null(query)){
      stop("Please add a query list to the function!\n")
    }
  }


  if(is.null(endpoint)){
    stop("Please add an endpoint to the function!\n")
  }

  if(is.null(query)){
    if(is.null(text_name)){
      stop("Please add name of text column!\n")
    }
    # Data is used
    rows_n <- nrow(data)
    data <- dplyr::select(data, paste0(text_name))
    data <- unlist(data[,1])
    max_length_txt <- max(nchar(data))

    if(max_length_txt > 1000){
      warning("The API cannot classify text snippets larger than 1000 characters!\nWe will cut all characters after 1000 chracters.\n")
      data <- stringr::str_trunc(data, 1000, "right")
    }

    query <- as.list(t(data))
    names(query) <- as.character(format(seq(from = 1, to = rows_n, by = 1), width = 3, flag = "0"))

    query
  }

  if(is.null(data)){
    rows_n <- length(list)
  }

  i <- 1
  batch_size <- 100
  while(i < rows_n){
    if(i == 1){
      k <- batch_size
    } else {
      k <- k + batch_size
    }
    if(k > rows_n){
      k <- rows_n
    }
    tmp <- classify(api_token = api_token, query = query[i:k], endpoint = endpoint)
    tmp <- as.data.frame(do.call(rbind, tmp))
    tmp <- tmp[,2]
    if(i == 1){
      classifications <- tmp
    } else {
      classifications <- c(classifications,tmp)
    }
    i <- k + 1
    Sys.sleep(5)
  }


  return(classifications)
}

##################################################################################################

#' This function allows you to build the needed list for the API to classify the text.
#' @param api_token string of the  token from your personal API access
#' @param endpoint character string with the name of the endpoint
#' @param query query of texts to classify in form of a list generated by query_maker().

#' @return a vector with predictions
#' @export
#'
#' @examples
#' \dontrun{
#' predictions <- classify(api_token = "", endpoint = "classify", query = query_list)
#' }

#' @importFrom dplyr select
#' @importFrom httr POST
#' @importFrom jsonlite fromJSON
#' @importFrom httr content
#' @importFrom stringr str_trunc

##################################################################################################
# Classify Function
##################################################################################################

classify <- function(api_token = NULL, query = NULL, endpoint = "classify"){

  if(is.null(api_token) & is.null(query) & is.null(endpoint)){
    stop("Please add all necessary agrument to the classify function!\n")
  }

  if(is.null(api_token)){
    stop("Please add the API token to the classify function!\n")
  }

  if(is.null(query)){
    stop("Please add a query list to the classify function!\n")
  }

  if(is.null(endpoint)){
    stop("Please add an endpoint to the classify function!\n")
  }

  httr::set_config(config(ssl_verifyhost = 0L))

  get_resp <- httr::POST(url= paste0("https://130.60.24.179/",endpoint,"/"),
                         body = query,
                         httr::add_headers(.headers = c(`AuthToken` = api_token)),
                         encode = "json",
                         content_type_json())
  if(get_resp$status_code == 200){
    #cat("Sucess!\n")
  } else {
    cat("Error in API Query!\n")
    stop()
  }


  result <- jsonlite::fromJSON(httr::content(get_resp, "text", encoding = "UTF-8"), simplifyDataFrame = T)

  return(result)
}
